# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unchainedOne', '0002_user_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='areas',
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
