# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unchainedOne', '0003_auto_20170527_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.IntegerField(),
        ),
    ]
